### ISSUE TITLE
如何做身份验证了？

### ISSUE THREAD

**Issue by guotingchaopr** [illuspas/Node-Media-Server#1]
首先感谢作者的源代码！
请问如何在此代码基础上来做上行流和下行流的身份验证呢？
希望您能给一些实现帮助或者是思路

**Comment by illuspas** [comment]
你可以参考Nginx模块里ngx_http_secure_link_module模块的原理和实现
http://nginx.org/en/docs/http/ngx_http_secure_link_module.html
目前大多数都采用这种鉴权模式

**Comment by guotingchaopr** [comment]
@illuspas 非常感谢！

**Comment by illuspas** [comment]
已内置了星域cdn风格的鉴权验证
