### ISSUE TITLE
我想对rtmp视频流进行切片处理我该怎么做？

### ISSUE THREAD

**Issue by lovelvyan** [illuspas/Node-Media-Server#10]
@illuspas 这个框架支持视频流切片吗？前几天我在你的另一个项目上问过你GOP cache相关问题，在这里我想您问一下我能不能通过切片解决延迟问题，把延迟降到2s以内，如果可以的话我应该怎么做？给点建议，谢谢！

**Comment by illuspas** [comment]
你说的视频流切片来降低延迟是个什么原理。
延迟2s以内还是很容易办到的呀，我们在那边讨论过，是关于播放时的优化。illuspas/nginx-rtmp-win32#23 
另外关系到延迟的，和视频编码器也有一定关系，比如用x264的话，-tune zerolatency也可以有效降低延迟的 [StreamingGuide](http://trac.ffmpeg.org/wiki/StreamingGuide#Latency)

**Comment by illuspas** [comment]
illuspas/nginx-rtmp-win32#23

**Comment by lovelvyan** [comment]
@illuspas 好的谢谢你的回答，我刚研究媒体流这块不久，好多不太清楚，我的意思是我把直播流切片，然后播放时直接播放m3u8的切片这样速度会不会快一些，我已经测试了效果也不好。针对hls播放直播流如果我想降低延迟从哪几个方面去做呢？nginx.conf该怎么配置？

**Comment by illuspas** [comment]
HLS 这类切片流从原理上就不是为低延迟设计的。
一个切片至少是一个关键帧区间吧，一个列表至少3个切片，编码器1秒一个关键帧的情况下都至少延迟3秒。

**Comment by lovelvyan** [comment]
@illuspas 嗯  我明白了，多谢指导！
