### ISSUE TITLE
Server slows down after first stream closes

### ISSUE THREAD

**Issue by oscarr-reyes** [illuspas/Node-Media-Server#101]
I'm planning to use this module in a web server to handle authentication and streaming rights, so most likely where i was working on security in the stream was on the event "prePublish" which should verify if the passed stream key is valid.. for this i am using a database with an ORM called `Sequelize`.

so the code is similar like this (the original has a bit different code but this example does the same result):

```Javascript
const mediaServer = require("node-media-server");
const utils           = require("./../utils");
const connection = require("./../unnamed/src/main/connection");
const userModel = connection.models.users;

const config = {
	rtmp: {
		port: 1935,
		chunk_size: 60000,
		gop_cache:true,
		ping: 60,
		ping_timeout: 30
	},
	http: {
		port: 8000,
		allow_origin: "*"
	}
};

const server = new mediaServer(config);

server.run();

server.on("prePublish", (id, path, args) => {
	console.log("[PRE-PUBLISH]:", id, path, args);

	userModel.findByStreamkey(utils.extractStreamkey(path))
		.then(user => {
			if(user == null) {
				const session = server.getSession(id);

				session.reject();
			}

			else {
				console.log(`Stream ${id} successfully published`);
			}
		});
});
```

The first stream connection works ok and everything goes smoothly, but right after i stop the streaming everything but the rtmp server slows down drastically, the same event is called but the function that makes the call to the database takes too long to execute, literally everything but rtmp gets too slow to the point that the browser thinks that the connection was interrumpted.

### System Specs:
**CPU**: Intel® Core™ i5-4440 CPU @ 3.10GHz × 4
**Memory**: 8GB DDR3 1600Mhz
**OS**: Linux Debian/Ubuntu 16.04.4 LTS 64-bit
**Node**: v8.11.3

**Comment by illuspas** [comment]
Please update version 1.4.1. 
I made a mistake, 1.3.5 later versions are affected.
And you need to be careful about using the new approach.
const { mediaServer } = require("node-media-server");

**Comment by oscarr-reyes** [comment]
Noted about the changes in the module, your fix is working, thank you
