### ISSUE TITLE
根据实例代码不能录制mp4,是怎么设置的？

### ISSUE THREAD

**Issue by dmbmingbin** [illuspas/Node-Media-Server#115]
const { NodeMediaServer } = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 60,
    ping_timeout: 30
  },
  http: {
    mediaroot: './media',
    port: 8080,
    allow_origin: '*'
  },
  auth: {
    play: true,
    publish: true,
    secret: 'nodemedia2017privatekey'
  },
  trans: {
    ffmpeg: 'D:\\ffmpeg\\bin\\ffmpeg.exe',
    tasks: [
      {
        app: 'vod',
        ac: 'aac',
        mp4: true,
        mp4Flags: '[movflags=faststart]',
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();

**Comment by yihub** [comment]
？ 是什么问题导致？
