### ISSUE TITLE
Only Single frame is given at a time

### ISSUE THREAD

**Issue by anuranBarman** [illuspas/Node-Media-Server#125]
I am trying to get the RTSP stream coming from my app but when I am trying to see it via VLC player it's only giving one frame. I tried to view it via http-flv by your given code it's reloading the next frame only if hit refresh of the browser. what is wrong? Do I have to change any parameter? I am using exact code snippet you mentioned in the repo

**Comment by talk2dug** [comment]
I am seeing this behavior. Is there are resolution to correcting this. 

Same hardware same version same config, worked at one time, and now I only get one frame.
