### ISSUE TITLE
max number of stream

### ISSUE THREAD

**Issue by TidusInSpira** [illuspas/Node-Media-Server#159]
Why can I only play up to 6 live streams?

**Comment by wangmaoguo** [comment]
why?

**Comment by TidusInSpira** [comment]
@wangmaoguo In the HTTP/1.1 protocol, browser clients have a certain number of requests for requests under the same domain name at the same time. Requests exceeding the limit will be blocked

![img](https://pic3.zhimg.com/80/faedeb3dae59455f6520d6a5dbf436e5_hd.jpg)

**Comment by wangmaoguo** [comment]
hello , can you give me the website about the limit?

**Comment by TidusInSpira** [comment]
@wangmaoguo [Roundup on Parallel Connections | High Performance Web Sites](http://www.stevesouders.com/blog/2008/03/20/roundup-on-parallel-connections/)
