### ISSUE TITLE
配置 如下：使用obs推流，在Mac下录mp4和hls正常，使用windows则录制和hls没有文件，请问这是什么回事？谢谢

### ISSUE THREAD

**Issue by dmbmingbin** [illuspas/Node-Media-Server#167]
const { NodeMediaServer } = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 60,
    ping_timeout: 30
  },
  http: {
    mediaroot: './media',
    port: 8080,
    allow_origin: '*'
  },
  /*https: {
    port: 8443,
    key:'./ssl/2_0758.com.cn.key',
    cert:'./ssl/1_0758.com.cn_bundle.crt',
  },*/
  /*auth: {
    play: true,
    publish: true,
    secret: 'nodemedia2017privatekey'javascript:;
  },*/
  trans: {
    ffmpeg: '/root/ffmpeg_sources/ffmpeg-4.1/ffmpeg',
    tasks: [
      {
        app: 'live',
        ac: 'aac',
        hls: true,
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
        dash: true,
        dashFlags: '[f=dash:window_size=3:extra_window_size=5]',
        mp4: true,
        mp4Flags: '[movflags=faststart]',
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();

**Comment by qiaowei361** [comment]
`const NodeMediaServer = require('node-media-server');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: 8000,
    mediaroot: './media',
    allow_origin: '*'
  },
   auth: {
    api : true,
    api_user: 'admin',
    api_pass: 'dywx@123',
  },
  trans: {
    ffmpeg: 'C:\\Program Files\\ffmpeg\\ffmpeg.exe',
    tasks: [
      {
        app: 'live',
        ac: 'aac',
        hls: true,
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
        dash: true,
        dashFlags: '[f=dash:window_size=3:extra_window_size=5]'
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();`


我上面的配置就可以使用手机播放，不过，有点延迟的厉害。
