### ISSUE TITLE
CORS issue with flv.js

### ISSUE THREAD

**Issue by Svish** [illuspas/Node-Media-Server#169]
Trying to get through this (at first glance) simple Open Broadcaster Software > Node Media Server > flv.js sample in a React with Redux course. But the video player seems to be blocked by a CORS issue?

> XHR GET http://localhost:9000/live/7.flv
> [IOController] > Loader error, code = -1, msg = NetworkError when attempting to fetch resource. index.js:1446
> [TransmuxingController] > IOException: type = Exception, code = -1, msg = NetworkError when attempting to fetch resource. index.js:1446
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:9000/live/7.flv. (Reason: CORS request did not succeed).[Learn More]

Is there a way I can configure the Node-Media-Server to supply the necessary CORS headers?

The current nms config is a direct copy of the sample in the readme, and basically the same with the flv.js code.

Here's a screenshot of "everything":

![capture](https://user-images.githubusercontent.com/142162/53608262-4a6f1980-3bc2-11e9-8f0c-83b0c1f5b053.PNG)

**Comment by illuspas** [comment]
This is not a CORS problem.
Your HTTP is on port 8000 and you are accessing 9000.

**Comment by Svish** [comment]
> This is not a CORS problem.
> Your HTTP is on port 8000 and you are accessing 9000.

🤦‍♂️ Unbelievable... One of these days someone should learn not to be programming late at night, blind on their own code...

Thanks! Free "solved issue" for the project. 😟🙃

**Comment by DaniHRE** [comment]
NO WAY I COMME HERE TRYING MY PROPBLEM AND SEE THAT!!!!
