### ISSUE TITLE
How to push relay to facebook and youtube with dynamic relay url

### ISSUE THREAD

**Issue by rrfaria** [illuspas/Node-Media-Server#252]
First of all, thanks for your incredible job.

I have created a live server where each user has your own live url like this:

/live/9p5oPcRzI

and to work with facebook and youtube rtmp I had to modify node-media-server on node_relay_server.js to remove "stream" on "conf.ouPath":

it it works pretty well to stream to youtube and facebook at same time 

```js 
onPostPublish(id, streamPath, args) {
    if (!this.config.relay.tasks) {
    return;
    }
    console.log("AKI", streamPath);
    let regRes = /\/(.*)\/(.*)/gi.exec(streamPath);
    let [app, stream] = _.slice(regRes, 1);
    console.log(stream);
    let i = this.config.relay.tasks.length;
    while (i--) {
      let conf = this.config.relay.tasks[i];
      let isPush = conf.mode === 'push';
      if (isPush && app === conf.app) {
      let hasApp = conf.edge.match(/rtmp:\/\/([^\/]+)\/([^\/]+)/);
      conf.ffmpeg = this.config.relay.ffmpeg;
      conf.inPath = `rtmp://127.0.0.1:${this.config.rtmp.port}${streamPath}`;
      conf.ouPath = hasApp ? `${conf.edge}` : `${conf.edge}`;
      let session = new NodeRelaySession(conf);
      session.id = id;
      session.on('end', (id) => {
        this.dynamicSessions.delete(id);
      });
      this.dynamicSessions.set(id, session);
      session.run();
      Logger.log('[Relay dynamic push] start', id, conf.inPath, ' to ', conf.ouPath);
      }
    }

  }
```

and in my project config 

```js
		relay: {
			ffmpeg: '/usr/bin/ffmpeg',
			tasks: [
				{
					app: 'live',
					mode: 'push',
					edge: 'rtmp://a.rtmp.youtube.com/live2/keyyoutube',
				},
				{
					app: 'live',
					mode: 'push',
					edge: 'rtmps://rtmp-pc.facebook.com:443/rtmp/keyface',
				}
			]
		},
```

but it is too said because all users will relay to the same url.

but what I want is each user having your own rtmp list and for instance those live:

/live/9p5oPcRzI

relay to:
```
rtmp://a.rtmp.youtube.com/live2/firstuserkeyyoutube
rtmps://rtmp-pc.facebook.com:443/rtmp/firstuserkeyface
```

and to another live:

/live/1p3oPdRas

relay to:
```
rtmp://a.rtmp.youtube.com/live2/seconduserkeyyoutube
rtmps://rtmp-pc.facebook.com:443/rtmp/seconduserkeyface
```

Without need restart the server when user add new one

How can I pass those parameters from de user?

I'm almost sure that I can use it:
```js
nms.on('postPublish', async (id, StreamPath, args) => {
```
to get from my database the user's relay

**Comment by digital1989** [comment]
I would like to know how to do this to.

@illuspas - Would you be able to help with this please?

**Comment by BrightSoul** [comment]
I need to do the same.
Thanks for any info you might provide.

**Comment by digital1989** [comment]
Hey @illuspas - I hope your well? Would you be able to help us with this please?

**Comment by kkrishnan90** [comment]
Doesn't seem to work for Facebook 'RTMPS' link. Only works on Youtube. Any help on this is much appreciated ! Thanks in advance !

**Comment by kkrishnan90** [comment]
I have got this working now ! I use the API to push and pull relays dynamically and in my API request body, I append the required URLs.

**Comment by digital1989** [comment]
What have you got working ?

**Comment by kkrishnan90** [comment]
Here's a fork of the same. I made adding Restful APIs to push

**Comment by digital1989** [comment]
@kkrishnan90 - I love to know how to set this up to test, Would you be able to help me with this ?

**Comment by kkrishnan90** [comment]
@digital1989  Sure thing !

**Comment by kkrishnan90** [comment]
@digital1989 Hope this helps you Nick ! Do let me know if you need any more support ! I would love to help people out !

**Comment by digital1989** [comment]
Hi, iv just tried the push api and it dosnt seem to be working.

I get a bad request when making a request to URL: http://<server ip>:<server port>/api/relay/push

Can you advise?

**Comment by kkrishnan90** [comment]
@digital1989  Please check the updated comment Nick ! its
```http://<server-ip>:<server-port>/api/relay/push

**Comment by digital1989** [comment]
@kkrishnan90  - 

I tried to do this POST call to the correct URL. 
`http://<server-ip>:<server-port>/api/relay/push`
{
                app        : 'live',
                mode       : 'push',
                vc         : 'libx264',
                ac         : 'aac',
                edge       :
                    'rtmp://127.0.0.1:1987/rtmp/<fb-stream-key>',
                appendName : false
}

Postman returns - Bad Request

**Comment by kkrishnan90** [comment]
@digital1989  Ok two things to check now :
1. Did you use my fork or did you use the original Node-Media-Server. If yes, how did you do an ```npm install``` ?
2. Did you install and enable ```stunnel``` facebook does not support RTMP since 1st May 2019. 
3. If you can paste your config code here it would be better for me to debug
4. Ensure once again that you're using my fork of this Node-Media-Server library as opposed to the original one.

Let me know your answers and I shall guide you to make it work as it definitely works for me, I even tested it a few hours ago.

**Comment by digital1989** [comment]
@kkrishnan90 I think we're getting our wires crossed here. I can stream to FB without stunnel just using the original rtmp-media-server and adding it to the config #196 

1. I have installed your forked version, with the new API routes.

2. When testing i managed to get a post request working with in postman using the following parameter, which looked like it started a dynamic push but then failed. 

`URL: http://<server-ip>:<server-port>/api/relay/push
HTTP METHOD: POST
JSON REQUEST BODY:`

`{
                "app"        : "live",
                "name"       : "1t5DmFyo",
                "vc"         : "libx264",
                "ac"         : "aac",
                "url"       :
                    "rtmps://live-api-s.facebook.com:443/rtmp/10157257881295831?s_bl=1&s_sml=3&s_sw=0&s_vt=api-s&a=Abz0IQFjssbHrFKs",
                "appendName" : false
}` 

I would love to know how to get this working - Add/Push relay without need to restart the config (dynamic push)

**Comment by kkrishnan90** [comment]
@digital1989 what do you mean it started and failed ? Can you show up your response and also the rtmp servers logs ? Would be able to decipher better with those.

**Comment by kkrishnan90** [comment]
Also did it show up on the events(Facebook live stream) that your live stream is connected ?

**Comment by digital1989** [comment]
@kkrishnan90 - I have done some more testing and i would like to say a big thank you for your update on this. I tested this from my https server with valid certificates and for sure it worked, dynamically sending to FB live and Youtube. When doing the POST call, your arguments that you mentioned above are not correct.

When running this call i received a response of BAD REQUEST
`URL: http://<server-ip>:<server-port>/api/relay/push
HTTP METHOD: POST
JSON REQUEST BODY:`
`{
                app        : 'live',
                mode       : 'push',
                vc         : 'libx264',
                ac         : 'aac',
                edge       :
                    'rtmp://127.0.0.1:1987/rtmp/<fb-stream-key>',
                appendName : false
}`

I changed the values as you can see below and the response comes back "OK". 
"mode" to "name" , name being the steam key. 
"edge" to "url", url being the place you want to push the stream. 

`URL: http://<server-ip>:<server-port>/api/relay/push
HTTP METHOD: POST
JSON REQUEST BODY:`
`{
                app        : 'live',
                name       : 'push',
                vc         : 'libx264',
                ac         : 'aac',
                url       :
                    'rtmp://127.0.0.1:1987/rtmp/<fb-stream-key>',
                appendName : false
}`

I would love to know a bit more about how this works and how you achieved this :).

**Comment by kkrishnan90** [comment]
@digital1989  Glad you got it worked mate ! Yeah sorry about that. It's ```url``` and not ```edge``` . I just noticed that typo as well. Lol. 😄 

Well, to let you know how things work and how I made it work this way.It's all about reading the source code of relevant modules and also a big thanks to @illuspas  for making the code so dynamic ! Kudos to his efforts !

P.S : Right now I'm working on a few more updates from the API side to delete unwanted streams through Http requests too. Coz, what I see right now is only relays to be pulled/pushed, streams to get or add. However, I would always prefer a ```delete``` to make sure the servers don't run streams that aren't required. 
So keep watching my forked library and I shall update those methods on the REST API soon.

**Comment by digital1989** [comment]
@kkrishnan90 - Hows things? Hows the API endpoints coming along? Do you know how i can cluster this RTMP server with load balancing and sticky sessions?

**Comment by Sk1zZo** [comment]
> @kkrishnan90 -
> 
> I tried to do this POST call to the correct URL.
> `http://<server-ip>:<server-port>/api/relay/push`
> {
> app : 'live',
> mode : 'push',
> vc : 'libx264',
> ac : 'aac',
> edge :
> 'rtmp://127.0.0.1:1987/rtmp/',
> appendName : false
> }
> 
> Postman returns - Bad Request

Hi, I have the same problem. I've printed the body in console and it write   
body: {},
route: Route { path: '/push', stack: [ [Object] ], methods: { post: true } },
[...]

How can I do?

**Comment by petecsaba** [comment]
Hello @kkrishnan90. I managed to get working the api, but when i post something to the api
`{
   "app":"live",
   "name":"push",
   "url":"rtmp://a.rtmp.youtube.com/live2/<key>",
   "appendName":"false"
}`
Postman says OK, but nothing happened. I use the media server with default configuration.

**Comment by ericprom** [comment]
@kkrishnan90 Any update on the API?

**Comment by adapterdigital** [comment]
@kkrishnan90 In POST JSON REQUEST BODY, can we send array 
`[{ app : 'live', name : 'push', vc : 'libx264', ac : 'aac', url : 'rtmp://127.0.0.1:1987/rtmp/<fb-stream-key>', appendName : false },{ app : 'live', name : 'push', vc : 'libx264', ac : 'aac', url : 'rtmp://127.0.0.1:1987/rtmp/<yt-stream-key>', appendName : false }]`

**Comment by Sk1zZo** [comment]
Hi, there is the api to delete the pushed stream?

**Comment by JohnTrabusca** [comment]
> @kkrishnan90 In POST JSON REQUEST BODY, can we send array
> [
> {
> app: 'live',
> name: 'push',
> vc: 'libx264',
> ac: 'aac',
> url: 'rtmp://127.0.0.1:1987/rtmp/fb-stream-key',
> appendName: false
> },
> {
> app: 'live',
> name: 'push',
> vc: 'libx264',
> ac: 'aac',
> url: 'rtmp://127.0.0.1:1987/rtmp/yt-stream-key',
> appendName: false
> }
> ]

Hi there, are you using the fork repo or the main repo to do this ? I've seen that is has beeb added but I can't figure out how to publish the livestream, can you help me out ?

**Comment by adapterdigital** [comment]
> > @kkrishnan90 In POST JSON REQUEST BODY, can we send array
> > [
> > {
> > app: 'live',
> > name: 'push',
> > vc: 'libx264',
> > ac: 'aac',
> > url: 'rtmp://127.0.0.1:1987/rtmp/fb-stream-key',
> > appendName: false
> > },
> > {
> > app: 'live',
> > name: 'push',
> > vc: 'libx264',
> > ac: 'aac',
> > url: 'rtmp://127.0.0.1:1987/rtmp/yt-stream-key',
> > appendName: false
> > }
> > ]
> 
> Hi there, are you using the fork repo or the main repo to do this ? I've seen that is has beeb added but I can't figure out how to publish the livestream, can you help me out ?

I can't push array to relay either. 

In order to push new relay to a relay server, you have to have an empty list of tasks in your config.

`relay: {
    // ffmpeg: 'C:/ffmpeg/bin/ffmpeg.exe', //Windows
    // ffmpeg: '/usr/bin/ffmpeg', //Linux
    ffmpeg: '/usr/local/bin/ffmpeg', //Mac
    tasks: []
  }`

Is this what you want to achieve? @JohnTrabusca

**Comment by JohnTrabusca** [comment]
Oh I see, one more question that I'm having some trouble to understand, are you using stunnel and why is it needed to see the rtmp as 127.0.0.1 ? Thanks for taking the time to help me out, Really appreciated

**Comment by JohnTrabusca** [comment]
@adapterdigital After a bit of research, this API has been implemented in the main repo, but instead of sending a json body, it's trough x-www-urlencoded, now I'm trying to figure out a way to stop the pushed stream through an API, but I think this has not been done yet

**Comment by hthetiot** [comment]
@kkrishnan90 Can you make a PR ?
- https://github.com/kkrishnan90/Node-Media-Server/issues/1

**Comment by kkrishnan90** [comment]
@hthetiot  I have created a PR for the same. Can you review and merge ?

**Comment by hthetiot** [comment]
Thank you @kkrishnan90 I'm not the maintainer @illuspas should review https://github.com/illuspas/Node-Media-Server/pull/361
