### ISSUE TITLE
Api for specific stream and current bitrate? 

### ISSUE THREAD

**Issue by mrsydster** [illuspas/Node-Media-Server#255]
I am looking for an API url that will display the data of a specific stream. E.g; 127.0.0.1:8888/api/stream/streamname

And I only see the total amount of bytes. Not the current bitrate.. Where to find this?!

**Comment by wangmaoguo** [comment]
可以的，你看一下项目中 controller里边 的 streams.js 里边有个 getStream方法

**Comment by mrsydster** [comment]
@wangmaoguo So what is the URL from the API? 
Lets say im streaminy with the key 'testing', how do I access the stats for that stream?

**Comment by DigiGroundJohn** [comment]
Hi, 

I know this question is a bit old, but @mrsydster  you answer did not work for me.
I download the code and have investigated the streams routes, and it is pretty clear there. 

  router.get('/:app/:stream', streamController.getStream.bind(context));
  
 My App name is "live" and my stream name is Test 
/api/streams/APP_NAME/STREAM_NAME
APP_NAME= setup in configuration.
STREAM_NAME=the name of your stream.


/api/streams/live/Test

Hopefully, this will help someone.
