### ISSUE TITLE
Is it normal with about 40 seconds delay in Lan?

### ISSUE THREAD

**Issue by loongtail** [illuspas/Node-Media-Server#264]
Whatever pushing video(mp4,flv) or capturing desktop, it always getting about 40 seconds delay, I am testing in Lan with ffplay(also with "-fflags nobuffer -flags low_delay") and libvlc. I dont think it's general, can anyone help?

my pushing command:
`ffmpeg -re -f gdigrab -i desktop -vcodec h264 -an -preset:v ultrafast -tune:v zerolatency -f flv rtmp://192.168.123.122/live/1`

**Comment by danielehrhardt** [comment]
> Whatever pushing video(mp4,flv) or capturing desktop, it always getting about 40 seconds delay, I am testing in Lan with ffplay(also with "-fflags nobuffer -flags low_delay") and libvlc. I dont think it's general, can anyone help?
> 
> my pushing command:
> `ffmpeg -re -f gdigrab -i desktop -vcodec h264 -an -preset:v ultrafast -tune:v zerolatency -f flv rtmp://192.168.123.122/live/1`

Same Problem here. Did you ever find a Solution?

**Comment by loongtail** [comment]
> > Whatever pushing video(mp4,flv) or capturing desktop, it always getting about 40 seconds delay, I am testing in Lan with ffplay(also with "-fflags nobuffer -flags low_delay") and libvlc. I dont think it's general, can anyone help?
> > my pushing command:
> > `ffmpeg -re -f gdigrab -i desktop -vcodec h264 -an -preset:v ultrafast -tune:v zerolatency -f flv rtmp://192.168.123.122/live/1`
> 
> Same Problem here. Did you ever find a Solution?

I had changed the protocol to rtsp with other library. It works but has to use c++ with MFC which I don't know how to deal with. Finally I use VNC as a concession of my solution.

**Comment by illuspas** [comment]
@loongtail, there is no key-frame interval is set in your ffmpeg parameters.
This causes the encoder to generate key frames irregularly and cache a lot of non-key frame on the server.

Look at the -g parameter.

**Comment by loongtail** [comment]
> @loongtail, there is no key-frame interval is set in your ffmpeg parameters.
> This causes the encoder to generate key frames irregularly and cache a lot of non-key frame on the server.
> 
> Look at the -g parameter.

Oh, thank you. It performs better now. It looks I can change back my original solution.
