### ISSUE TITLE
How to access published streams?

### ISSUE THREAD

**Issue by RationalCoding** [illuspas/Node-Media-Server#3]
Where are streams published? Are they exposed as a RTMP stream from the server, or do I need to read directly from the Bufferpool?

Any advice would be appreciated.

**Comment by illuspas** [comment]
The published streams already exposed as a RTMP stream.You just need to play it.

**Comment by RationalCoding** [comment]
Are they on the main route? What port? I must be missing something as I've not been able to find them after some time.

Is it `rtmp://localhost:80/live/STREAM_NAME` or similar?

**Comment by illuspas** [comment]
This may be a coding problem.The current version is only supported H.264/AAC streams.

**Comment by RationalCoding** [comment]
Where would I expect to find them if everything was working as intended?

**Comment by illuspas** [comment]
Test re-streaming a file to server using h.264+aac
`ffmpeg -re -i demo1.flv -c:v h264 -c:a aac  -f flv rtmp://localhost/live/stream_name`  
then
`ffplay rtmp://localhost/live/stream_name`

**Comment by RationalCoding** [comment]
Ok, so then it must be on my end. Thanks so much for your help!
