### ISSUE TITLE
I can't restream to youtube.

### ISSUE THREAD

**Issue by mwanielista** [illuspas/Node-Media-Server#311]
This part of app.js, don't send stream to youtube. I made everything with instructions from descriptions. How can I send video to youtube?
relay: {
  ffmpeg: '/usr/local/bin/ffmpeg',
  tasks: [
    {
      app: 'live',
      mode: 'push',
      edge: 'rtmp://a.rtmp.youtube.com/live2/yt_key',
    }
  ]
}

**Comment by chrisspiegl** [comment]
Most likely this comment with the new config parameter will help you:

https://github.com/illuspas/Node-Media-Server/issues/196#issuecomment-610819126

Please close this issue if the comment mentioned does what you expect. If not, let me know, and I'll see what I can do.

**Comment by brtmvdl** [comment]
Following!
