### ISSUE TITLE
How to Simulcast to Social Media?

### ISSUE THREAD

**Issue by CodeBradley** [illuspas/Node-Media-Server#317]
How would I go about pushing an incoming RTMP stream out to YouTube Live for instance? With NGINX I would use a push directive in the config, for instance. Is there something relative to that here? The idea is to have many incoming RTMP streams that can be broadcasted to each broadcasters respective social media accounts.

**Comment by chrisspiegl** [comment]
The setup you are describing is something that I have plaid with as well with the NMS.
However, I have only been able to do this by coding some parts myself to dynamically add and remove relays to the stream keys that are in the system.
This can be done by listening to the "prePublish" event.

**Comment by CodeBradley** [comment]
Thanks for the tip @chrisspiegl, I'm checking this out now 👍

**Comment by CodeBradley** [comment]
You are the man @chrisspiegl ! This works great so far. How many connections do you think this can handle on DigitalOcean smallest container? 

Edit: I just noticed your comment asking about the rtmploader repo, you're a wealth of info :) Thanks for making that post too lol

**Comment by chrisspiegl** [comment]
Hey @CodeBradley, always happy to help. If you solved your challenge, could you close this issue or check in if you still need help?
