### ISSUE TITLE
Replace AMF

### ISSUE THREAD

**Issue by Zaseth** [illuspas/Node-Media-Server#325]
Hi 👋

I've noticed that the AMF library in this repository is pretty unsupported. If needed, check out my library [here](https://github.com/Zaseth/bytearray-node). It fully supports AMF0 and AMF3, as well as the entire ByteArray package.

**Comment by illuspas** [comment]
Hi, I've seen your project. It's great! 👍 
However, this project is working well so far. 
Flash will be out of service by the end of the year, so there isn't much demand for AMF3.

**Comment by Zaseth** [comment]
Thank you, and I understand. Let's not reinvent the wheel here then. Cheers!
