### ISSUE TITLE
No Transcoding to remuxing to hls?

### ISSUE THREAD

**Issue by bakamaru** [illuspas/Node-Media-Server#327]
As I've setup new repo and setup node media server.I've installed and followed every steps mentioned and rtmp seems working but as soon as i go for hls/dash stream,media directory is empty and no trans coding were done? Is there any steps to get hls or dash stream?

**Comment by ac00perw** [comment]
I solved this by adding ac: 'copy' to my trans block which now looks like this in full:

  trans: {
    ffmpeg: '/usr/bin/ffmpeg',
    tasks: [
      {
        app: 'live',
        hls: true,
        ac: 'copy',
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
        dash: true,
        dashFlags: '[f=dash:window_size=3:extra_window_size=5]'
      }   
    ]
  }

**Comment by bakamaru** [comment]
have a look. I'm using following codes 
`const NodeMediaServer = require('./');

const config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60
  },
  http: {
    port: 8000,
    mediaroot: './media',
    allow_origin: '*'
  },
  trans: {
    ffmpeg: './ffmpeg/ffmpeg.exe',
     tasks: [
      {
        app: 'live',
        hls: true,
	ac: 'copy',
        hlsFlags: '[hls_time=2:hls_list_size=3:hls_flags=delete_segments]',
        dash: true,
        dashFlags: '[f=dash:window_size=3:extra_window_size=5]'
      }
    ]
  }
};

var nms = new NodeMediaServer(config)
nms.run();`
I've pushed stream to rtmp server 
`ffmpeg -re -i output.mp4 -c:v libx264 -preset superfast -tune zerolatency -c:a aac -ar 44100 -f flv rtmp://localhost/living/test`
rtmp published  command invoked and served but transmuxing /hls/dash not hapening... why is that? 
![image](https://user-images.githubusercontent.com/1064348/80005765-c07bc180-84e3-11ea-8027-dbaf834a5fac.png)

**Comment by ac00perw** [comment]
Maybe the path to ffmpeg.exe?

**Comment by bakamaru** [comment]
If i specify other than that result error like this 
![image](https://user-images.githubusercontent.com/1064348/80006891-39c7e400-84e5-11ea-8ef9-9482827e8acc.png)
So i guess that was the correct path for system.
ps I'm running on windows 10.

**Comment by bakamaru** [comment]
I got it!!!! It was just spelling mistake on rtmp address.I've used rtmp://localhost/living/test which should be rtmp://localhost/live/test.
Anyway thank you very much for your valuable time @ac00perw, really appreciated :)

**Comment by ac00perw** [comment]
Nice! Glad it was a simple fix.
