### ISSUE TITLE
HLS Multiple quality outputs

### ISSUE THREAD

**Issue by byeze** [illuspas/Node-Media-Server#337]
Hi!

I want to know how I can output hls with the ability to adapt to the user bandwith. Example: From a 1920x1080 video input, I want 4 quality outputs (360p, 480p, 720p, 1080p).
There are some guides in the internet on how to do it with ffmpeg but I don't know how to implement it with NodeMediaServer.

Thank you!

**Comment by tuanva-hw** [comment]
Up!

**Comment by jamessandison** [comment]
Have a look at what @johndavedecano has done with it!

https://github.com/johndavedecano/node-rtmp-hls

**Comment by byeze** [comment]
Thank you very much @jamessandison 
Now closing issue!

**Comment by tuanva-hw** [comment]
> Have a look at what @johndavedecano has done with it!
> 
> https://github.com/johndavedecano/node-rtmp-hls

It seems that it has not been done correctly. All outputs have the same resolution
