### ISSUE TITLE
Numer of simultaneous connections

### ISSUE THREAD

**Issue by tomsol432** [illuspas/Node-Media-Server#338]
Hello,
I just got interested in making my own streaming platform. I have set up example code on three different machines:
-VPS with single core processor and 2 GB of ram (Debian 9 based)
-Raspberry PI3 (Newest Raspbian)
-Virtual machine on my PC with 6 cores@100% cap, 4GB of RAM (Ubuntu Server)

And I have a problem with number of connection I can make at the same time. I am using Node based http server, hosting single website with flvjs player.

My results are:
-VPS: 12 simultaneous connections
-RPI3: 6
-VM: 6

By testing load on each machine I can't see obvious bottleneck on any of them. Is there any configuration I am not aware of? Any clues?

[Edit] I actually forgot to say that I am able to connect to my website but the player is grayed out and only thing I see is gray video area with loading animation.

Thanks for help,
Tomasz

**Comment by phprad** [comment]
Am facing this same issue. It seems like the maximum number of connection NMS can accept is 6.

Please any solution to this.

**Comment by illuspas** [comment]
Maybe you should try to use websocket-flv protocol.
Just need modify http:// to ws://

**Comment by tomsol432** [comment]
Hello, I have actually managed to find this solution two days ago! Using ws:// allows me to setup more connections, the number of it if determined by the speed of server output connection. In my case (100 mbps connection), and 2500 kbps stream allows me for around 30 clients watching stream.

**Comment by harrymelka** [comment]
Hello 

How do you configure the ws, it's the flv file that is created when you launch the stream but I don't manage to get it. 

This is my config:

```js
const config = {
  logType: 3,
  
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 30,
    ping_timeout: 60,
  },
  http: {
    port: 8080,
    mediaroot: "./media",
    allow_origin: "*",
    api: true,
  },
  trans: {
    ffmpeg: "/usr/bin/ffmpeg",
    tasks: [
      {
        app: "live",
        hls: true,
        rtmp:true,
        hlsFlags: "[hls_time=2:hls_list_size=3:hls_flags=delete_segments]",
        dash: true,
        dashFlags: "[f=dash:window_size=3:extra_window_size=5]",
        'websocket-flv': true, // Not working
      },
    ],
  },
};

var nms = new NodeMediaServer(config);
nms.run();
``` 

With that you get the flv or do I need to use ffmpeg in the config ?
