### ISSUE TITLE
Documentation on Relay API

### ISSUE THREAD

**Issue by JohnTrabusca** [illuspas/Node-Media-Server#339]
Hello, can anyone help me with the Relay API, I'm trying to post to /api/relay/push an json body like this: `{
	app: 'live',
	name: 'LIlZB0c2ae',
	url: 'rtmps://live-api-s.facebook.com:443/rtmp/[fb-key]',
	appendName: false
}`

But unfortunately it keeps returning 400 Bad Request. I don't know what else I can do.

**Comment by sandrocsimas** [comment]
It's because you're sending the payload as json, but you need to send as x-www-form-urlencoded.
