### ISSUE TITLE
Can developers share the React sources for /admin?

### ISSUE THREAD

**Issue by CodeBradley** [illuspas/Node-Media-Server#376]
I'm trying to figure out how flv is converted into a blob object

**Comment by CodeBradley** [comment]
https://github.com/illuspas/Node-Media-Server-Admin/

**Comment by pvtulsiram538** [comment]
@CodeBradley  https://github.com/illuspas/Node-Media-Server-Admin is not found

**Comment by CodeBradley** [comment]
Wayback? This is crazy old, not sure what it was about anymore.
