### ISSUE TITLE
Connection Refused 

### ISSUE THREAD

**Issue by MalcolmTomisin** [illuspas/Node-Media-Server#378]
When I try to publish a live stream from a video file as directed in the documentation 

> ffmpeg -re -i INPUT_FILE_NAME -c:v libx264 -preset veryfast -tune zerolatency -c:a aac -ar 44100 -f flv rtmp://localhost/live/STREAM_NAME
>
I get this error below

> [tcp @ 0x558be7da50] Connection to tcp://localhost:1935 failed: Connection refused
[rtmp @ 0x558be2d370] Cannot open connection tcp://localhost:1935
rtmp://localhost/live/STREAM_NAME: Connection refused
>

I am running this on a nvidia jetson tx2 ubuntu 18.04, really looking forward to getting around this problem and understanding the documentation better

**Comment by MalcolmTomisin** [comment]
Figured out that I might be getting this error because the node server is not running when I run

> node app.js

**Comment by byeze** [comment]
Please, close the issue. Thanks!
