### ISSUE TITLE
[Suggest] Support to RTMPS

### ISSUE THREAD

**Issue by meirinaldojunior** [illuspas/Node-Media-Server#388]
Some streaming platforms support only the RTMPS protocol, is there any provision for implementation of this module?

**Comment by CodeBradley** [comment]
Have you already checked out these?

https://github.com/illuspas/Node-Media-Server/issues/284 and https://github.com/illuspas/Node-Media-Server/issues/269

**Comment by hthetiot** [comment]
This dockerfile make RTMPS work for facebook out of the box:
- https://github.com/illuspas/Node-Media-Server/pull/356

TLDR get a version 4.2.2 of ffmpeg with open SSL that also works.
