### ISSUE TITLE
FLV to ws protocol

### ISSUE THREAD

**Issue by mamoyko** [illuspas/Node-Media-Server#39]
Any Idea how can i convert FLV into websocket protocol?

Thanks

**Comment by branditz** [comment]
@mamoyko - hey I think it now working here.. better use jsmpeg (codec mpeg1video)

**Comment by illuspas** [comment]
You can use ffmpeg to re-push.
```
ffmepg -re -i FLV -c copy -f flv rtmp://server-ip/live/stream
```
Then you can access through ws://server-ip:8000/live/stream.flv

**Comment by branditz** [comment]
Hi,

Great, let me try that.

Thanks
