### ISSUE TITLE
Stream works fine, but player stuck on one frame

### ISSUE THREAD

**Issue by dxf** [illuspas/Node-Media-Server#414]
Hi all,

Installed the latest NMS on macOS 10.14, and it's working fine. (No HLS support for some reason but alas it doesn't matter)

Trying to get the FLV stream to work, on the Node-Media-Server admin page it plays just fine but if I copy the code from one of the examples in the README to my own HTML page, I get stuck on one frame and then no video plays. Can anyone provide a simple web player for the FLV stream that doesn't encounter this issue?

Thanks!

Daf

**Comment by anthonyloukinas** [comment]
Also seeing this issue just following the README documentation. Fresh install, on Windows 10/Ubuntu and I'm only ever seeing a single frame at a time indefinitely. 

```
/**
 * NodeMediaServer Configuration
 */
const config = {
    logType: 3,
    rtmp: {
        port: 1935,
        chunk_size: 60000,
        gop_cache: true,
        ping: 30,
        ping_timeout: 60
    },
    http: {
        port: 8000,
        allow_origin: '*',
    }
};
```

**Comment by anthonyloukinas** [comment]
@dxf I actually fixed my issue... Firefox was blocking audio/video autoplay which I found out by inspecting the console. You need to allow it up in the URL box if that's your issue
