### ISSUE TITLE
RTMP 播放BUG

### ISSUE THREAD

**Issue by thunderyan** [illuspas/Node-Media-Server#43]
1）同一个设备如果同时播放同一条RTMP流，第二次播放的那条流一定卡死。
1）同一个设备，先用FLV播放同一条流，再用RTMP播放同一条流，RTMP必卡死。

**Comment by thunderyan** [comment]
无论是不是同一个浏览器。只要打开同一条流就有这个问题。

**Comment by thunderyan** [comment]
并且每次卡的时间不一样，有的很快，有的很久。

**Comment by illuspas** [comment]
设备是什么，用什么播放的

**Comment by thunderyan** [comment]
设备电脑，或者手机都会有这样的问题。
播放器随便一个rtmp播放器，例如：srs就可以了。
昨晚测试了一下，发现只要在同一个网络下，连不管是不是同一设备都会这样！
例如：连着同一wifi，电脑A打开视频流可以流畅播放，电脑B打开视频流可以看到画面但是卡住，注意是同一视频流。

目前看到的效果是只有rtmp有这个问题，ws(s)，或http(s)都是正常的。

**Comment by illuspas** [comment]
根据你的描述，我这儿还是重现不了这种情况出来
你的nodejs运行环境是什么，操作系统，版本，架构

**Comment by thunderyan** [comment]
不是吧？在我这里是必现的哦。不管是不是我本地电脑，还是线上服务器都是必现的。
操作系统试过，WIN10/CENTOS6（7） 都是这样的。
NODE版本是：v8.1.3
架构：用你的说明跑起来服务器，然后随便ffmpeg或者fme或者android等设备推送一条流，然后播放。

我再复述一下过程：
假设播放流  A为：rtmp://a.rtmp.com/live/stream
1)  在设备上用RTMP播放器（我试过好几个都是会的）播放A（开始播放）。
2)  重复步骤1）但是不要关闭 1），这里不管2个打开的rtmp是不是在同一个浏览器都会。
PS： 最后发现连设备都无关了，只要在同一网络下（例如：WIFI）只要有播放，第二个播放者的RTMP视频就会卡住。
还有一种情况就是：
1）在设备上用HTTP(S)/WS(S)播放视频流A；
2）在设备上用RTMP播放视频流A，这种情况下也是会卡住；

有试过不同的操作系统，不同的NODE版本，都会有这个问题。

**Comment by thunderyan** [comment]
"rtmp": {
    "port": 1935,
    "chunk_size": 6000,
    "gop_cache": false,
    "ping": 60,
    "ping_timeout": 60
  },
  "http": {
    "port": 8001,
    "allow_origin": "*"
  },
  "auth": {
    "play": false,
    "publish": true,
    "secret": "nodemedia2017privatekey"
  },
  "https": {
    "port": 8443,
    "key": "./default/privatekey.pem",
    "cert": "./default/certificate.pem"
  }

这个是我的配置，试过GOP 跟 chunk_size 改过也是一样的效果。

第二个播放者，是有数据来的，但是好像就是卡在第一帧。

**Comment by illuspas** [comment]
仍然无法复现 贴出你
http://ip:8001/api/streams
的内容

**Comment by thunderyan** [comment]
刚才做了一些详细的测试，应该是视频源的问题。换了一些其他的源就没有出现这个问题。
麻烦关闭这个BUG，谢谢协助。

**Comment by illuspas** [comment]
😂
