### ISSUE TITLE
Secret Key same stream Path

### ISSUE THREAD

**Issue by canerd7u** [illuspas/Node-Media-Server#431]
I installed the demo application and wanted to run tests.

When I check it, the secret key we entered into the OBS system and the streampath look the same. Any user can access this secret key from my frontend codes and initiate broadcasts on behalf of the user.

How can I prevent this?

**Comment by crvgilbertson** [comment]
Here's how I did it:

1. Assign a stream token to each streamer in a database of your choosing (skip this if you are using this alone)
2. Add this stream token as an argument in your stream path. For example, in OBS, if you wanted use the stream path "test" with a secret token "123", the stream key field would read ""test?token=123".
3. If you used the above, add this code to verify that the secret token is "123"

nms.on('prePublish', (id, StreamPath, args) => {
    console.log('\n\n[NodeEvent on prePublish]', `id=${id} StreamPath=${StreamPath} args=${JSON.stringify(args)}`);
    let session = nms.getSession(id);
    if(args.token != '123'){
        session.reject();
    }
});

Alternatively, if you have multiple streamers, you will need to add a database check to ensure the user's stream token is correct.

**Comment by mgcountss** [comment]
Thank you!!!

**Comment by LPBlive** [comment]
Hey!
I tried to store the streamkeys in a mysql database and fetch them in the preConnect Event. Everything works fine, exept the Session.reject(). When i call this function in the callback of the database function, obs will connect, disconnect, reconnect, disconnect till i close the stream in obs or shutting down NMS. Any idea to prevent that?
