### ISSUE TITLE
Performance Test

### ISSUE THREAD

**Issue by asterisk360-admin** [illuspas/Node-Media-Server#432]
Did someone has been able to perform a performance test of node media with high load?

1,000 concurrent conections or more 

@illuspas @hthetiot @snowron @KM8Oz @nsthorat
Any feed back is apreciated

Regards

**Comment by KM8Oz** [comment]
I will inform as soon as possible

**Comment by dangolbeeker** [comment]
Hello any update?

**Comment by gigabyteservice** [comment]
@KM8Oz any update?

**Comment by KM8Oz** [comment]
none brother we closed the website after a while. but as I told you last
time it's working fine for 100 stream max in a 20 cores server. in four
qualities 360/480/720 HLS.

**Comment by pvtulsiram538** [comment]
I tested with 1004 connections with 32 GB vCPU . No load . But there is an issue 
[https://github.com/illuspas/Node-Media-Server/issues/435](url) coming
