### ISSUE TITLE
Transcode stop but rmtp publish is still running

### ISSUE THREAD

**Issue by flavioribeirojr** [illuspas/Node-Media-Server#435]
Hi there!

I absolutely love this project. Was a life saver for my project.

First, here is my use case:
I have an electron app that uses FFMPEG to send IP camera streams to Node-Media-Server hosted on a EC2 instance. I am using transcoding to generate HLS files that users can play on a mobile app and website.

On the electron app I have a routine that restarts ffmpeg command if it exits. On Node-Media-Server I have used the events to notify the viewers when a stream is available or offline.

Now the issue: sometimes Transcode just stop when the publishing is still happening. That way my app can't restart FFMPEG because it is still running even though the transcoding is not.

When the transcoding stop this was the log displayed:

```
3/16/2021 01:55:43 1 [INFO] [rtmp play] Close stream. id=2ZRT4FJT streamPath=/live/6048f9e6d650ab0007d1ee6d streamId=1

3/16/2021 01:55:43 1 [INFO] [rtmp disconnect] id=2ZRT4FJT

3/16/2021 01:55:43 1 [INFO] [Transmuxing end] /live/6048f9e6d650ab0007d1ee6d
```

Any help or guidance will be much apreciated.

**Comment by rehamkhawajahere** [comment]
Same issue. Any solution?

**Comment by hthetiot** [comment]
related i think https://github.com/illuspas/Node-Media-Server/pull/355 

node_trans_session.js:
```difff
- this.ffmpeg_exec.kill();
 + this.ffmpeg_exec.stdin.write('q');
```

Can you try this see if that fix the issue.

**Comment by flavioribeirojr** [comment]
@hthetiot  FFMPEG is exiting after `[Transmuxing end]`. The issue is after that the rmtp socket keep receiving the stream data. It should have stopped.

**Comment by hthetiot** [comment]
> @hthetiot FFMPEG is exiting after `[Transmuxing end]`. The issue is after that the rmtp socket keep receiving the stream data. It should have stopped.

Ok. I don't experience that with that change, not sure why.

**Comment by WaseemAlkurdi** [comment]
@flavioribeirojr Since you're fine with HLS, why not just go with `nginx-hls-live-module` ? It has HLS support out of the box.
I'm curious about one thing: would the latency with HLS be too high for your use case (i.e. cameras) ?

**Comment by flavioribeirojr** [comment]
I have decided to migrate to https://github.com/arut/nginx-rtmp-module

So far I have no issues.
