### ISSUE TITLE
RTMP publish to NMS error. core_av line 182

### ISSUE THREAD

**Issue by zoro5722** [illuspas/Node-Media-Server#46]
what is u8 stand for?
I am doing publish with ffmpeg. Simply copy from TS stream. Not work for u8 not defined.
Publisher:
ffmpeg -i http://localhost/source.ts -acodec copy -vcodec copy -f flv rtmp://localhost/live/test
 
End as:
[rtmp handleVideoMessage] Parse VideoTagHeader frame_type=1 codec_id=7 codec_name=H264
/home/bs/content-site/rtmpServer/node_modules/node-media-server/node_core_av.js:182
        for (n = 0; n < (cf_idc != 3 ? u8 : u12); n++) {
                                       ^

ReferenceError: u8 is not defined
    at readH264SpecificConfig (/home/bs/content-site/rtmpServer/node_modules/node-media-server/node_core_av.js:182:40)

MORE INFO:
the TS stream contains H.264 High Profile. I set the TS stream to Main Profile, it works. But don't know why.

**Comment by illuspas** [comment]
Please send your source.ts to me so that I can do a better test.
