### ISSUE TITLE
Is it possible to include custom information in an RTMP packet header?

### ISSUE THREAD

**Issue by stefanjaspers** [illuspas/Node-Media-Server#465]
I need to be able to send custom data along with an RTMP packet. I was wondering if the RTMP protocol supports a way to do this.

**Comment by MaximevanderSmissen** [comment]
Yes it is

**Comment by BartFijneman** [comment]
> I need to be able to send custom data along with an RTMP packet. I was wondering if the RTMP protocol supports a way to do this.

Yes

**Comment by stefanjaspers** [comment]
Figured it out by adding custom commands which we can send from the encoder to the server.
