### ISSUE TITLE
Dynamic and Static Pulling

### ISSUE THREAD

**Issue by talk2dug** [illuspas/Node-Media-Server#468]
I am working on a project that will have hundreds of cameras and we need to auto populate the edge nodes. On the edge nodes we are creating a static pull and then the front edge nodes dynamicly pull those feeds and feed them to the user. 

In a previous post I wrote that we are having issues with the cameras we have they are telling the player its sending 100 frames a sec. TO get around this we have to use a few switches in ffmpeg. My question is, is there a way to set these flags in the static pull section of the config?

-re
      -rtsp_transport tcp
      -i rtsp://admin:PASSWORD@${nodeIP}:554/cam/realmonitor?channel=1&subtype=1
      -codec copy 
      -f flv 
      rtmp://127.0.0.1/streams/${nodeName}-camera1

**Comment by illuspas** [comment]
Whether this option is used in the configuration?
```
      rtsp_transport : 'tcp' 
```


```
relay: {
  ffmpeg: '/usr/local/bin/ffmpeg',
  tasks: [
    {
      app: 'cctv',
      mode: 'static',
      edge: 'rtsp://admin:admin888@192.168.0.149:554/ISAPI/streaming/channels/101',
      name: '0_149_101',
      rtsp_transport : 'tcp' 
    }
  ]
}
```

**Comment by illuspas** [comment]
Or maybe  '-re' is not used here:
https://github.com/illuspas/Node-Media-Server/blob/master/src/node_relay_session.js#L28
