### ISSUE TITLE
socket disconnecting with Info [rtmp disconnect] on centOS server

### ISSUE THREAD

**Issue by Vikash-git7** [illuspas/Node-Media-Server#494]
I am trying to create a Node-media-server but after stating the server I got these success Info logs.

 [INFO] Node Media Server v2.3.8
 [INFO] Node Media Rtmp Server started on port: 1935
 [INFO] Node Media Http Server started on port: 8000
 [INFO] Node Media WebSocket Server started on port: 8000
 [INFO] Node Media Trans Server started for apps: [ live ] , MediaRoot: ./media, ffmpeg version: 4.4-static

But after this, I am constantly getting an INFO log of RTMP disconnect with ID. 
[INFO] [rtmp disconnect] id=I5L1S965
[INFO] [rtmp disconnect] id=VQWKE9UU

After debugging I found that This is coming from - **onSocketClose** hook.

May I ask why these RTMP disconnect logs are printing on centos as code is working fine on the local machine?
Note - Is this related to **socket.remoteAddress** as my centos server is returning remoteAddress as my VIP IP.

Thank you very much for your time!
Appreciate

**Comment by Abdullahi247** [comment]
Make sure to open ports 80 and 443 on your production server

**Comment by Vikash-git7** [comment]
@Abdullahi247 Ports are open. This is not creating any problem. Application is working fine I just wanted to know why this is happening.

**Comment by Abdullahi247** [comment]
Alright
