### ISSUE TITLE
access stream stats from NodeMediaServer instance

### ISSUE THREAD

**Issue by ariemeow** [illuspas/Node-Media-Server#51]
Hi,

Can i access the information on /api/streams from nms instance at main js?

```
var nms = new NodeMediaServer(config)
nms.run();
```

something like 

`nms.getStreamStats();`

is it possible?

Thanks

**Comment by illuspas** [comment]
You can copy the 'getStreams' function in api/controllers/streams.js, do not serialize 'stats',  just return it.

**Comment by njavilas2015** [comment]
How to do it, they would give me a small example to guide me, I'm lost, I'm looking for where the variable this.sessions comes from in streams.js
