### ISSUE TITLE
Stop HLS file from been deleted after stream ended

### ISSUE THREAD

**Issue by lewatt23** [illuspas/Node-Media-Server#524]
Hell guys, please am facing this issue, my hls files are been deleted after stream endeded, can someone help me on how to fix that?  thanks.

**Comment by JohnTrabusca** [comment]
Hey @lewatt23 it's natural behavior from the script itself, however you can modify remove the line from the script that does this, the file that you have to modify is this https://github.com/illuspas/Node-Media-Server/blob/219ca691fda874c94712e4ba86a023948940409d/src/node_trans_session.js#L89 that way you will be able to keep your .ts files

**Comment by lewatt23** [comment]
thanks
