### ISSUE TITLE
Is it possible to forward the stream?

### ISSUE THREAD

**Issue by DaveStein** [illuspas/Node-Media-Server#57]
The server works as I expect it to. I can stream to it and then test that it works by opening the rtmp URL with VLC player.

I need to actually receive the stream on my server just for some orchestration purposes before sending it to another location for the actual broadcast. Is there any way to do this with your package?

**Comment by DaveStein** [comment]
I guess this ask is what Relay -> Push does in https://github.com/arut/nginx-rtmp-module/wiki/Directives#relay

**Comment by illuspas** [comment]
Yes, I've implemented this function in the master branch.
When I finish the development, I will submit a new version, which will be updated by npm.
You can try it by cloning the master branch.

**Comment by DaveStein** [comment]
That's amazing!

**Comment by DaveStein** [comment]
Hm do you have any examples? I am looking at https://github.com/illuspas/Node-Media-Server/blob/master/node_relay_server.js and am not sure how to pass config to make sure it relays to another endpoint. I am guessing I add a `relay` key to the config for `NodeMediaServer` but am not sure how to point at other endpoint, or what other required config there may be.

**Comment by DaveStein** [comment]
https://github.com/illuspas/Node-Media-Server/blob/master/node_relay_server.js#L27 has typo in console for `trans` instead of `relay`. Figured it'd be just as easy for you to commit that change to master rather than me making a one-word PR for you to review :P

**Comment by illuspas** [comment]
First, you need to compile ffmpeg.
Install the compiled ffmpeg to any directory and specify the full path in config.relay.ffmpeg 
```
/usr/local/bin/ffmpeg
```

For example,If you want :
OBS push stream ==to==> Your Node-Media-Server ==to==>  CDN Server
What you need is ‘push’ mode.
```
 tasks: [
      {
        app: 'live',
        mode: 'push',
        edge: 'rtmp://www.destination.com/whereithinkitgoes'
      }, 
]
```

**Comment by DaveStein** [comment]
Thanks so much!
