### ISSUE TITLE
IPv6 fix

### ISSUE THREAD

**Issue by JaPaBu** [illuspas/Node-Media-Server#64]
Hey if you specify '0.0.0.0' IPv6 is not supported.

change:  this.httpsServer.listen(this.sport, '0.0.0.0', () => {

to:          this.httpsServer.listen(this.sport, () => {

for every occurance of '0.0.0.0'

This should fix that issue

**Comment by illuspas** [comment]
Yes, I know. I banned it in the previous version.

**Comment by illuspas** [comment]
Already fixed
