### ISSUE TITLE
Ghost ffmpeg instance

### ISSUE THREAD

**Issue by jhdscript** [illuspas/Node-Media-Server#66]
Hello, I m using NMS to relay more than 500 sources streams to 100 users (friends and family) and I have some issues.

I m using only relay functions defined with this conf:

`
var config = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 60,
    ping_timeout: 30
  },
  http: {
    port: 8000,
    allow_origin: '*'
  },

  relay: {
    ffmpeg: ffmpeg_path,
    tasks: [
      {
        app: 'live',
        mode: 'pull',
        edge: 'http://127.0.0.1:8888'
      }
    ]
  }
};
`

It appears in some time ffmpeg doesn't close and publisher still alive with 0 subscribers.

How can I "kill" ghosted instances ?

Tahnx a lot for your job !

**Comment by illuspas** [comment]
There will be such unexpected problems.
I will solve them in later versions.

**Comment by illuspas** [comment]
Maybe you can try this one. 
Comment and uncomment , in the node_relay_session.js
```
  end() {
    this.ffmpeg_exec.kill('SIGINT');
    //this.ffmpeg_exec.stdin.write('q');
  }
```

**Comment by jhdscript** [comment]
Ok i try it

**Comment by jhdscript** [comment]
I have this error in log maybe it can help you:

2018-4-9 12:01:58 [ERROR] Unknown command { cmd: 'FCSubscribe' }
