### ISSUE TITLE
那个。。。怎么验证啊？

### ISSUE THREAD

**Issue by zhenruyan** [illuspas/Node-Media-Server#7]
如题

**Comment by illuspas** [comment]
配置里,播放和发布是可以分别开启验证的.像下面这样就只开发布鉴权.
```
auth: {
    play: false,
    publish: true,
    secret: 'nodemedia2017privatekey'
  }
```
nodemedia2017privatekey就是鉴权KEY

具体的算法说明,看星域cdn的吧,我懒得写了
http://docs.xycdn.com/%E8%A7%86%E9%A2%91%E7%9B%B4%E6%92%AD/%E8%AE%BE%E7%BD%AE%E8%AF%B4%E6%98%8E/%E7%9B%B4%E6%92%AD%E9%89%B4%E6%9D%83%E6%9C%BA%E5%88%B6/%E9%89%B4%E6%9D%83%E7%AE%97%E6%B3%95

**Comment by zhenruyan** [comment]
多谢
