### ISSUE TITLE
Auth not checked when publishing?

### ISSUE THREAD

**Issue by maikmerten** [illuspas/Node-Media-Server#84]
Hi there,

thanks for developing and sharing Node-Media-Server, which looks excellent!

I'm trying to set up a local streaming server and want to prevent arbitrary sources to publish a stream. Thus I put added authentication to the example server instantiation code:

```JavaScript
const NodeMediaServer = require("node-media-server");

const nmsconfig = {
  rtmp: {
    port: 1935,
    chunk_size: 60000,
    gop_cache: true,
    ping: 60,
    ping_timeout: 30
  },
  http: {
    port: 8000,
    allow_origin: '*'
  },
  auth: {
    publish: true,
    secret: 'testpassword'
  }
};

var nms = new NodeMediaServer(nmsconfig);
nms.run();
```

However, in OBS Studio I can still publish streams without providing any "sign=..." parameter. I assume I'm missing something?

(I don't want to restrict playback, only publishing, which is why I omitted "play" from the auth config.)

I'm using version 1.3.3 of Node-Media-Server.

**Comment by illuspas** [comment]
Are you making a request from the local machine?
This is always allowed.

**Comment by maikmerten** [comment]
Thanks for your response! Oh, I wasn't aware that publishing locally is always allowed and indeed, I tested things on my local machine. I'll recheck once deployed on a remote machine.

**Comment by maikmerten** [comment]
I can confirm now that authentication works for remote machines. Sorry for bothering you!

**Comment by fazila-mehtab** [comment]
Remotely authentication is working for me as well but with RTMP protocol not with HTTP why it is?

**Comment by Sina-KH** [comment]
@illuspas 
Thanks. Maybe it's better to mention this issue in the auth section of readme file.
